# Gruber Darker for Alacritty
# Theme author: John Gruber
# Ported by: klephron

[colors.primary]
background = "#181818"
foreground = "#E4E4E4"

[colors.cursor]
text = "#181818"
cursor = "#FFDD33"

[colors.selection]
text = "#F4F4FF"
background = "#453D41"

[colors.normal]
black = "#181818"
red = "#F43841"
green = "#73D936"
yellow = "#FFDD33"
blue = "#96A6C8"
magenta = "#9E95C7"
cyan = "#95A99F"
white = "#F5F5F5"

[colors.bright]
black = "#52494E"
red = "#F43841"
green = "#73D936"
yellow = "#FFDD33"
blue = "#96A6C8"
magenta = "#9E95C7"
cyan = "#95A99F"
white = "#FFFFFF"
